version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      expo:
        patterns:
          - 'expo'
          - 'expo-*'
          - 'jest-expo'
          - 'eslint-config-expo'
      react-native:
        patterns:
          - 'react-native'
          - 'react-native-*'
          - 'nativewind'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - 'react-test-renderer'
          - '@types/react'
      dev-dependencies:
        dependency-type: 'development'
        exclude-patterns:
          - 'jest-expo'
          - 'eslint-config-expo'
          - 'react-test-renderer'
          - '@types/react'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
